# Generated by Django 5.1.5 on 2025-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_depot', models.DateField()),
                ('date_retrait', models.DateField(blank=True, null=True)),
                ('Regler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='super_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('quantite', models.CharField(max_length=50)),
                ('valeur', models.CharField(max_length=50)),
                ('date_depot', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='super_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('quantite', models.CharField(max_length=50)),
                ('valeur', models.CharField(max_length=50)),
                ('date_depot', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='super_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('quantite', models.CharField(max_length=50)),
                ('valeur', models.CharField(max_length=50)),
                ('date_depot', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='super_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('quantite', models.CharField(max_length=50)),
                ('valeur', models.CharField(max_length=50)),
                ('date_depot', models.DateField()),
            ],
        ),
    ]
