# Generated by Django 5.1.5 on 2025-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_1',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_1',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_1',
            name='valeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_2',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_2',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_2',
            name='valeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_3',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_3',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_3',
            name='valeur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_4',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_4',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='super_4',
            name='valeur',
            field=models.IntegerField(),
        ),
    ]
