# Generated by Django 5.1.5 on 2025-01-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0002_alter_super_1_index_alter_super_1_quantite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_1',
            old_name='index',
            new_name='litre',
        ),
        migrations.RenameField(
            model_name='super_2',
            old_name='index',
            new_name='litre',
        ),
        migrations.RenameField(
            model_name='super_3',
            old_name='index',
            new_name='litre',
        ),
        migrations.RenameField(
            model_name='super_4',
            old_name='index',
            new_name='litre',
        ),
    ]
