# Generated by Django 5.1.5 on 2025-01-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0003_rename_index_super_1_litre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='depot',
        ),
        migrations.RenameField(
            model_name='super_1',
            old_name='date_depot',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='super_2',
            old_name='date_depot',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='super_3',
            old_name='date_depot',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='super_4',
            old_name='date_depot',
            new_name='date',
        ),
    ]
