# Generated by Django 5.1.5 on 2025-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0004_delete_depot_rename_date_depot_super_1_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_1',
            old_name='litre',
            new_name='jour',
        ),
        migrations.RenameField(
            model_name='super_2',
            old_name='litre',
            new_name='jour',
        ),
        migrations.RenameField(
            model_name='super_3',
            old_name='litre',
            new_name='jour',
        ),
        migrations.RenameField(
            model_name='super_4',
            old_name='litre',
            new_name='jour',
        ),
        migrations.AddField(
            model_name='super_1',
            name='veille',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super_2',
            name='veille',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super_3',
            name='veille',
            field=models.IntegerField(default=43),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super_4',
            name='veille',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
