# Generated by Django 5.1.5 on 2025-01-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0006_rename_date_super_1_date1_rename_jour_super_1_jour1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='super_2',
        ),
        migrations.DeleteModel(
            name='super_3',
        ),
        migrations.DeleteModel(
            name='super_4',
        ),
        migrations.RenameField(
            model_name='super_1',
            old_name='veille1',
            new_name='veille',
        ),
    ]
