# Generated by Django 5.1.5 on 2025-01-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0007_delete_super_2_delete_super_3_delete_super_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veille', models.IntegerField()),
                ('jour', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('valeur', models.IntegerField()),
                ('date', models.DateField()),
                ('unite', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
