# Generated by Django 5.1.5 on 2025-01-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0008_super'),
    ]

    operations = [
        migrations.DeleteModel(
            name='super_1',
        ),
    ]
