# Generated by Django 5.1.5 on 2025-01-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0010_gazoil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazoil',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='super',
            name='unite',
        ),
    ]
