# Generated by Django 5.1.5 on 2025-01-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0011_remove_gazoil_unite_remove_super_unite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veille', models.IntegerField()),
                ('jour', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('valeur', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
