# Generated by Django 5.1.5 on 2025-01-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0012_mairie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mairie',
            name='type_pay',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
