# Generated by Django 5.1.5 on 2025-01-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0013_mairie_type_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='type',
            field=models.IntegerField(),
        ),
    ]
