# Generated by Django 5.1.5 on 2025-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0017_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifiant', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
