# Generated by Django 5.1.5 on 2025-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0018_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essence',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
