# Generated by Django 5.1.5 on 2025-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_Essence', '0019_alter_essence_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_cuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuve', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Gazoil',
        ),
        migrations.DeleteModel(
            name='Super',
        ),
    ]
